# Generated by Django 2.1 on 2019-04-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20190426_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='createdate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='createdate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='createdate',
            field=models.CharField(max_length=20),
        ),
    ]
